local Plug = vim.fn['plug#']

vim.call('plug#begin','~/.vim/plugged')

Plug('nvim-lua/plenary.nvim')
Plug('mbbill/undotree')
Plug('kyazdani42/nvim-web-devicons')
Plug('kyazdani42/nvim-tree.lua')
Plug('neoclide/coc.nvim', {['branch'] = 'release'})
Plug('mattn/emmet-vim')
Plug('tpope/vim-dadbod')
Plug('kristijanhusak/vim-dadbod-ui')
Plug('easymotion/vim-easymotion')
Plug('preservim/tagbar')
Plug('mhinz/vim-signify', {['branch'] =  'legacy'})
Plug('pangloss/vim-javascript')
Plug('vim-python/python-syntax')
Plug('plasticboy/vim-markdown')
Plug('nvim-treesitter/nvim-treesitter', {['do']= ':TSUpdate'})
Plug('kwsp/halcyon-neovim')
Plug('lukas-reineke/indent-blankline.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('windwp/nvim-autopairs')
Plug('akinsho/bufferline.nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-neorg/neorg')
Plug('Pocco81/HighStr.nvim')

vim.call('plug#end')

--config plugins
require('setup.lua-tree')
require('setup.treesitter')
require('setup.indent-line')
require('setup.autopairs')
require('setup.bufferline')
require('setup.lualine')
require('setup.norg')
require('setup.hight')
